# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
                ('query', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.IntegerField()),
                ('responded', models.BooleanField()),
                ('created_on', models.DateTimeField()),
                ('modified_on', models.DateTimeField()),
                ('exit_type', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sync.Run')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sync.Run')),
            ],
        ),
    ]
